# Generated by Django 4.1.3 on 2024-03-26 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_id_alter_bid_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='auctioneer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
