# Generated by Django 5.0.3 on 2024-04-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlisting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='status',
            field=models.CharField(default='Open', max_length=8),
        ),
    ]
